/**
 * fix-mp4.js
 * Universal MP4 Metadata & Duration Normalizer for In-Browser MediaRecorder Exports
 * 
 * Ensures that fragmented MP4 (fMP4) video files generated by Chromium/Safari MediaRecorder
 * have accurate duration headers in mvhd, tkhd, and mdhd boxes so video players, mobile
 * devices (iOS / Android), and social platforms recognize the full video duration and seek cleanly.
 */

(function (root, factory) {
  if (typeof define === 'function' && define.amd) {
    define([], factory);
  } else if (typeof module === 'object' && module.exports) {
    module.exports = factory();
  } else {
    root.ysFixMp4Duration = factory();
  }
}(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

  function readUInt32(view, offset) {
    return view.getUint32(offset, false);
  }

  function writeUInt32(view, offset, value) {
    view.setUint32(offset, value >>> 0, false);
  }

  function readUInt64(view, offset) {
    const high = view.getUint32(offset, false);
    const low = view.getUint32(offset + 4, false);
    return (BigInt(high) << 32n) | BigInt(low);
  }

  function writeUInt64(view, offset, bigValue) {
    const b = BigInt(bigValue);
    const high = Number((b >> 32n) & 0xFFFFFFFFn);
    const low = Number(b & 0xFFFFFFFFn);
    view.setUint32(offset, high, false);
    view.setUint32(offset + 4, low, false);
  }

  function getFourCC(view, offset) {
    return String.fromCharCode(
      view.getUint8(offset),
      view.getUint8(offset + 1),
      view.getUint8(offset + 2),
      view.getUint8(offset + 3)
    );
  }

  function patchMoovBox(buffer, durationMs) {
    const view = new DataView(buffer);
    const totalLen = buffer.byteLength;
    let offset = 0;

    let movieTimescale = 1000;
    let targetMovieDuration = BigInt(Math.max(1000, Math.round(durationMs)));

    // 1. Locate moov box
    let moovOffset = -1;
    let moovSize = 0;

    while (offset + 8 <= totalLen) {
      let size = readUInt32(view, offset);
      const type = getFourCC(view, offset + 4);
      let headerSize = 8;

      if (size === 1) {
        if (offset + 16 > totalLen) break;
        size = Number(readUInt64(view, offset + 8));
        headerSize = 16;
      } else if (size === 0) {
        size = totalLen - offset;
      }

      if (type === 'moov') {
        moovOffset = offset;
        moovSize = size;
        break;
      }

      if (size <= 0) break;
      offset += size;
    }

    if (moovOffset === -1) {
      return buffer; // moov not found, return as-is
    }

    // 2. Parse inside moov
    const moovEnd = Math.min(totalLen, moovOffset + moovSize);
    let cur = moovOffset + 8;

    // First pass: Find mvhd to get movie timescale & patch mvhd duration
    let scanPtr = cur;
    while (scanPtr + 8 <= moovEnd) {
      const bSize = readUInt32(view, scanPtr);
      const bType = getFourCC(view, scanPtr + 4);
      if (bSize < 8) break;

      if (bType === 'mvhd') {
        const version = view.getUint8(scanPtr + 8);
        if (version === 0) {
          // mvhd v0: size(4), 'mvhd'(4), ver(1), flags(3), ctime(4), mtime(4), timescale(4), duration(4)
          movieTimescale = readUInt32(view, scanPtr + 20) || 1000;
          targetMovieDuration = BigInt(Math.round((durationMs * movieTimescale) / 1000));
          writeUInt32(view, scanPtr + 24, Number(targetMovieDuration));
        } else if (version === 1) {
          // mvhd v1: size(4), 'mvhd'(4), ver(1), flags(3), ctime(8), mtime(8), timescale(4), duration(8)
          movieTimescale = readUInt32(view, scanPtr + 28) || 1000;
          targetMovieDuration = BigInt(Math.round((durationMs * movieTimescale) / 1000));
          writeUInt64(view, scanPtr + 32, targetMovieDuration);
        }
        break;
      }
      scanPtr += bSize;
    }

    // Second pass: Traverse trak boxes & mvex
    scanPtr = cur;
    while (scanPtr + 8 <= moovEnd) {
      const bSize = readUInt32(view, scanPtr);
      const bType = getFourCC(view, scanPtr + 4);
      if (bSize < 8) break;

      if (bType === 'trak') {
        patchTrakBox(view, scanPtr, scanPtr + bSize, durationMs, targetMovieDuration);
      } else if (bType === 'mvex') {
        patchMvexBox(view, scanPtr, scanPtr + bSize, targetMovieDuration);
      }

      scanPtr += bSize;
    }

    return buffer;
  }

  function patchTrakBox(view, trakStart, trakEnd, durationMs, targetMovieDuration) {
    let cur = trakStart + 8;
    let trackTimescale = 1000;

    while (cur + 8 <= trakEnd) {
      const size = readUInt32(view, cur);
      const type = getFourCC(view, cur + 4);
      if (size < 8) break;

      if (type === 'tkhd') {
        const ver = view.getUint8(cur + 8);
        if (ver === 0) {
          // tkhd v0: size(4), 'tkhd'(4), ver(1), flags(3), ctime(4), mtime(4), trackId(4), rsv(4), duration(4)
          writeUInt32(view, cur + 28, Number(targetMovieDuration));
        } else if (ver === 1) {
          // tkhd v1: size(4), 'tkhd'(4), ver(1), flags(3), ctime(8), mtime(8), trackId(4), rsv(4), duration(8)
          writeUInt64(view, cur + 36, targetMovieDuration);
        }
      } else if (type === 'mdia') {
        // Find mdhd inside mdia
        let mdiaCur = cur + 8;
        const mdiaEnd = Math.min(trakEnd, cur + size);
        while (mdiaCur + 8 <= mdiaEnd) {
          const mSize = readUInt32(view, mdiaCur);
          const mType = getFourCC(view, mdiaCur + 4);
          if (mSize < 8) break;

          if (mType === 'mdhd') {
            const mVer = view.getUint8(mdiaCur + 8);
            if (mVer === 0) {
              // mdhd v0: ctime(4), mtime(4), timescale(4), duration(4)
              trackTimescale = readUInt32(view, mdiaCur + 20) || 1000;
              const trackDur = BigInt(Math.round((durationMs * trackTimescale) / 1000));
              writeUInt32(view, mdiaCur + 24, Number(trackDur));
            } else if (mVer === 1) {
              // mdhd v1: ctime(8), mtime(8), timescale(4), duration(8)
              trackTimescale = readUInt32(view, mdiaCur + 28) || 1000;
              const trackDur = BigInt(Math.round((durationMs * trackTimescale) / 1000));
              writeUInt64(view, mdiaCur + 32, trackDur);
            }
            break;
          }
          mdiaCur += mSize;
        }
      }

      cur += size;
    }
  }

  function patchMvexBox(view, mvexStart, mvexEnd, targetMovieDuration) {
    let cur = mvexStart + 8;
    while (cur + 8 <= mvexEnd) {
      const size = readUInt32(view, cur);
      const type = getFourCC(view, cur + 4);
      if (size < 8) break;

      if (type === 'mehd') {
        const ver = view.getUint8(cur + 8);
        if (ver === 0) {
          writeUInt32(view, cur + 12, Number(targetMovieDuration));
        } else if (ver === 1) {
          writeUInt64(view, cur + 12, targetMovieDuration);
        }
        break;
      }
      cur += size;
    }
  }

  /**
   * Fixes an MP4 Blob by ensuring all duration headers are correctly populated.
   * @param {Blob} blob - The raw MP4 Blob from MediaRecorder
   * @param {number} durationMs - The accurate duration in milliseconds
   * @param {function} callback - Callback receiving the fixed Blob
   */
  function fixMp4Duration(blob, durationMs, callback) {
    if (!blob || blob.size === 0) {
      if (typeof callback === 'function') callback(blob);
      return;
    }

    const reader = new FileReader();
    reader.onload = function () {
      try {
        const buffer = reader.result;
        patchMoovBox(buffer, durationMs);
        const fixedBlob = new Blob([buffer], { type: blob.type || 'video/mp4' });
        if (typeof callback === 'function') callback(fixedBlob);
      } catch (err) {
        console.warn('Error in fixMp4Duration:', err);
        if (typeof callback === 'function') callback(blob);
      }
    };
    reader.onerror = function () {
      if (typeof callback === 'function') callback(blob);
    };
    reader.readAsArrayBuffer(blob);
  }

  return fixMp4Duration;
}));
